Repository cygnusb2b/endeavor-business-media-newsletters, pull requests merged in 2020-09, with the labels that each got.

#221 Integrate DPM with EmailX and promotions
  package.json
  packages/common/components/blocks/leaderboard-primary.marko
  packages/common/components/blocks/marko.json
  packages/common/components/dpm/content.marko
  packages/common/components/dpm/emailx.marko
  packages/common/components/dpm/marko.json
  packages/common/components/elements/advertisement.marko
  packages/common/components/elements/content-link.marko
  packages/common/components/elements/marko.json
  packages/common/components/elements/primary-image.marko
  packages/common/components/marko.json
  packages/common/components/style-b/blocks/simple-card.marko
  packages/common/package.json
  tenants/americanmachinist/package.json
  tenants/asumag/package.json
  tenants/bulktransporter/package.json
  tenants/contractingbusiness/package.json
  tenants/contractormag/package.json
  tenants/dentaleconomics/package.json
  tenants/distributedenergy/package.json
  tenants/ecmweb/package.json
  tenants/ehstoday/package.json
  tenants/electricalmarketing/package.json
  tenants/electronicdesign/package.json
  tenants/evaluationengineering/package.json
  tenants/ewweb/package.json
  tenants/fleetowner/package.json
  tenants/flowcontrolnetwork/package.json
  tenants/forgingmagazine/package.json
  tenants/foundrymag/package.json
  tenants/hpac/package.json
  tenants/hpnonline/package.json
  tenants/hydraulicspneumatics/package.json
  tenants/industryweek/package.json
  tenants/machinedesign/package.json
  tenants/mhlnews/package.json
  tenants/mlo-online/package.json
  tenants/mwrf/package.json
  tenants/newequipment/package.json
  tenants/powerelectronics/package.json
  tenants/processingmagazine/package.json
  tenants/rdhmag/config/core.js
  tenants/rdhmag/package.json
  tenants/refrigeratedtransporter/package.json
  tenants/rermag/package.json
  tenants/sourcetoday/package.json
  tenants/tdworld/package.json
  tenants/trailerbodybuilders/package.json
  tenants/trucker/package.json
  tenants/vspc/package.json
  yarn.lock
Labels: dependencies, enhancement

#231 Removed invalid < character
  packages/common/components/style-a/blocks/leaderboard.marko
Labels: bug

#236 Update @base-cms/marko-newsletters-email-x dependencies to 1.41.0
  packages/common/package.json
  tenants/americanmachinist/package.json
  tenants/asumag/package.json
  tenants/bulktransporter/package.json
  tenants/contractingbusiness/package.json
  tenants/contractormag/package.json
  tenants/dentaleconomics/package.json
  tenants/distributedenergy/package.json
  tenants/ecmweb/package.json
  tenants/ehstoday/package.json
  tenants/electricalmarketing/package.json
  tenants/electronicdesign/package.json
  tenants/evaluationengineering/package.json
  tenants/ewweb/package.json
  tenants/fleetowner/package.json
  tenants/flowcontrolnetwork/package.json
  tenants/forgingmagazine/package.json
  tenants/foundrymag/package.json
  tenants/hpac/package.json
  tenants/hpnonline/package.json
  tenants/hydraulicspneumatics/package.json
  tenants/industryweek/package.json
  tenants/machinedesign/package.json
  tenants/mhlnews/package.json
  tenants/mlo-online/package.json
  tenants/mwrf/package.json
  tenants/newequipment/package.json
  tenants/powerelectronics/package.json
  tenants/processingmagazine/package.json
  tenants/rdhmag/package.json
  tenants/refrigeratedtransporter/package.json
  tenants/rermag/package.json
  tenants/sourcetoday/package.json
  tenants/tdworld/package.json
  tenants/trailerbodybuilders/package.json
  tenants/trucker/package.json
  tenants/vspc/package.json
  yarn.lock
Labels: dependencies
